defmodule StripeManaged.Invoice do
  @moduledoc """
  Retrieve invoices generated by Managed Payments subscriptions.

  Invoices include the `hosted_invoice_url` field which gives
  customers access to a Stripe-hosted invoice page.

  Note: One-off invoices cannot be created on Managed Payments
  subscriptions outside of billing periods.
  """

  alias StripeManaged.Client

  @path "/v1/invoices"

  @doc "Retrieves an invoice by ID."
  @spec retrieve(String.t(), keyword()) :: Client.response()
  def retrieve(id, opts \\ []) do
    Client.get("#{@path}/#{id}", opts)
  end

  @doc "Lists invoices. Filter by `customer`, `subscription`, `status`, etc."
  @spec list(map(), keyword()) :: Client.response()
  def list(params \\ %{}, opts \\ []) do
    Client.get(@path <> "?" <> URI.encode_query(Client.flatten_params(params)), opts)
  end

  @doc "Returns a lazy Stream of all invoices, auto-paginating."
  @spec list_all(map(), keyword()) :: Enumerable.t()
  def list_all(params \\ %{}, opts \\ []) do
    Client.list_paginated(@path, params, opts)
  end

  @doc "Retrieves the upcoming invoice for a subscription."
  @spec upcoming(map(), keyword()) :: Client.response()
  def upcoming(params \\ %{}, opts \\ []) do
    Client.get(@path <> "/upcoming?" <> URI.encode_query(Client.flatten_params(params)), opts)
  end
end
